# Generated by Django 4.1.7 on 2023-03-01 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=22)),
                ('bank_name', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_card_number', models.CharField(blank=True, max_length=22, null=True)),
                ('target_account_type', models.CharField(blank=True, choices=[('person', 'Person'), ('company', 'Company')], max_length=10, null=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('action', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('_transaction_id', models.CharField(max_length=50, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
            ],
        ),
    ]
