# Generated by Django 4.1.7 on 2023-05-31 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_user_info_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('card_number', models.CharField(max_length=16)),
                ('retail', models.BooleanField()),
                ('user', models.ManyToManyField(related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
