# Generated by Django 4.1.7 on 2023-05-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='retail',
            new_name='is_business',
        ),
    ]
