# Generated by Django 4.1.7 on 2023-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
